[package]
name = "Sniffy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.33.0"
clap = {version = "4.2.5", features = ["derive"]}
text_io = "0.1.12"
spinners = "4.1.0"
